/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "znjotcubcutqhpkylhju"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpuam90Y3ViY3V0cWhwa3lsaGp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzMzUwMDksImV4cCI6MjA4ODkxMTAwOX0.Vq1aKQlnuku6d_-sxX-de7MjGu8ml8WKId9llhuuMtU"